apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-frontend
  template:
    metadata:
      labels:
        app: youtube-frontend
    spec:
      containers:
      - name: frontend
        image: shamashaik19/youtube-frontend:latest
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-frontend
spec:
  type: LoadBalancer
  selector:
    app: youtube-frontend
  ports:
  - port: 80
    targetPort: 4000

