apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-backend
  labels:
    app: youtube-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-backend
  template:
    metadata:
      labels:
        app: youtube-backend
    spec:
      containers:
      - name: backend
        image: shamashaik19/youtube-backend:latest  # Replace with your image name
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: youtube-backend
spec:
  selector:
    app: youtube-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

